# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieBuff' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieBuff
pod 'SwiftLint'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'WKAwesomeMenu'
pod 'SnapKit', '~> 4.0.0'
pod 'FSPagerView'
pod 'YouTubePlayer-Swift'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 4.0'
pod 'Fabric'
pod 'Crashlytics'

end
